from __future__ import annotations

from typing import Protocol


class ObjectStorage(Protocol):
    async def ensure_ready(self) -> None: ...

    async def healthcheck(self) -> bool: ...

    async def put_bytes(self, key: str, content: bytes, content_type: str) -> None: ...

    async def get_bytes(self, key: str) -> bytes: ...

    async def exists(self, key: str) -> bool: ...
